AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy static site with Cognito login

Resources:
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${WebBucket.Arn}/*"

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: PulsePointUserPool
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: PulsePointWebClient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: pulsepoint-login-demo
      UserPoolId: !Ref UserPool

Outputs:
  WebsiteURL:
    Value: !GetAtt WebBucket.WebsiteURL
    Description: URL of the static website

  CognitoLoginURL:
    Value: !Sub "https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&response_type=token&redirect_uri=http://localhost"
    Description: Hosted UI login URL
