AWSTemplateFormatVersion: '2010-09-09'
Description: Static website with Cognito login

Parameters:
  AppName:
    Type: String
    Default: pulsepointcare
    Description: Lowercase name for your app

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AppName}-userpool"
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: webclient
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      CallbackURLs:
        - !Sub "http://${StaticSiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
      LogoutURLs:
        - !Sub "http://${StaticSiteBucket}.s3-website-${AWS::Region}.amazonaws.com"

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${AppName}-auth-${AWS::AccountId}"
      UserPoolId: !Ref UserPool

Outputs:
  WebsiteURL:
    Description: Static site URL
    Value: !GetAtt StaticSiteBucket.WebsiteURL

  CognitoHostedLogin:
    Description: Hosted UI Login URL
    Value: !Sub "https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?response_type=token&client_id=${UserPoolClient}&redirect_uri=http://${StaticSiteBucket}.s3-website-${AWS::Region}.amazonaws.com"
